version: "3.12"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000" #mapping local 8000 port to docker 8000 port
    volumes:
      - ./app:/app  #mapping local app folder to docker app folder
    command: 
     sh -c "python manage.py runserver 0.0.0.0:8000"   